### ISSUE TITLE
Issues List: When you are submitting new issue, plz read

### ISSUE THREAD

**Issue by yuuki410** [ExistOS-Team/ExistOS-For-HP39GII#78]
To do List:
- [ ] #74 Save setting such as contrast, CPU minimum frequency
- [ ] #58 More type fonts
- [ ] #59 Series problem of `OSLoader` (Details below)
- [ ] #73 #67 etc. UI design needs to be optimized.
- [ ] Updating document.
- [ ] ~#43 Yes it is on the to do list. Yes it is.~

Series problem of `OSLoader`:
(To do)
